### ISSUE TITLE
Limit queue

### ISSUE THREAD

**Issue by baires** [sosedoff/musicbot#11]
Thanks for the bot, is a really nice starter for us who sucks at go.

One of problem that Im facing right now is that the queue always adds 10 tracks. I have been digging around the source and I noticed that. Is there any way to limit the queue to 1 track?

On `bot/handlers.go` I saw a `limit:10` so I tough that changing that limit to 1 will work, but no.

I also change the spotify endpoint to look for tracks instead of albums.

Any hint will be appreciated

**Comment by sosedoff** [comment]
> On bot/handlers.go I saw a limit:10 so I tough that changing that limit to 1 will work, but no.

What happens if you change the limit to 1? Any errors? I need more info in order to troubleshoot. 

> I also change the spotify endpoint to look for tracks instead of albums.

You can use https://github.com/sosedoff/musicbot/blob/master/spotify/api.go#L65 to make searches for albums, see docs https://developer.spotify.com/web-api/search-item/ for more details. I haven't looked at how mopidy handles album (instead of track) playback so i cant really comment much on this one.

**Comment by baires** [comment]
When I change the limit to 1, nothing happens, It brings 10 results always. So my guess is that there a flag somewhere asking for 10 results. Will look into that.

I will try force limit here https://github.com/sosedoff/musicbot/blob/master/spotify/api.go#L65

Thanks for your time!

**Comment by sosedoff** [comment]
There's something wrong on your end. I just changed https://github.com/sosedoff/musicbot/blob/af4a18967b643beda423542369b0234ab443fe1a/bot/handlers.go#L155 to 1 and it worked just as expected, only 1 track was added to the queue. Are you sure you're running `make` every time you change the code?

**Comment by baires** [comment]
Yup, totally miss the `make` :-1: 

I will give it another try
